from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Test(object):
    def setupUi(self, Test):
        Test.setObjectName("Test")
        Test.resize(514, 150)
        Test.setMinimumSize(QtCore.QSize(400, 150))
        Test.setMaximumSize(QtCore.QSize(800, 158))
        self.gridLayout = QtWidgets.QGridLayout(Test)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(Test)
        self.lineEdit.setMinimumSize(QtCore.QSize(64, 32))
        self.lineEdit.setMaximumSize(QtCore.QSize(600, 32))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 1, 1, 1)
        self.Choose = QtWidgets.QLabel(Test)
        self.Choose.setMinimumSize(QtCore.QSize(64, 32))
        self.Choose.setMaximumSize(QtCore.QSize(64, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Choose.setFont(font)
        self.Choose.setTextFormat(QtCore.Qt.AutoText)
        self.Choose.setScaledContents(False)
        self.Choose.setWordWrap(False)
        self.Choose.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.Choose.setObjectName("Choose")
        self.gridLayout.addWidget(self.Choose, 1, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(Test)
        self.pushButton_2.setMinimumSize(QtCore.QSize(64, 32))
        self.pushButton_2.setMaximumSize(QtCore.QSize(64, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Test)
        self.pushButton.setMinimumSize(QtCore.QSize(64, 32))
        self.pushButton.setMaximumSize(QtCore.QSize(64, 32))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(Test)
        self.label.setMinimumSize(QtCore.QSize(64, 32))
        self.label.setMaximumSize(QtCore.QSize(64, 32))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Test)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(64, 32))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(600, 32))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Test)
        self.label_2.setMinimumSize(QtCore.QSize(64, 32))
        self.label_2.setMaximumSize(QtCore.QSize(64, 32))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)

        self.retranslateUi(Test)
        QtCore.QMetaObject.connectSlotsByName(Test)

    def retranslateUi(self, Test):
        _translate = QtCore.QCoreApplication.translate
        Test.setWindowTitle(_translate("Test", "Form"))
        self.Choose.setText(_translate("Test", "Choose"))
        self.pushButton_2.setText(_translate("Test", "PushButton"))
        self.pushButton.setText(_translate("Test", "PushButton"))
        self.label.setText(_translate("Test", "TextLabel"))
        self.label_2.setText(_translate("Test", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Test = QtWidgets.QWidget()
    ui = Ui_Test()
    ui.setupUi(Test)
    Test.show()
    sys.exit(app.exec_())
